"use client";

import { useState, useEffect, useCallback } from "react";

type Brief = {
  id: string;
  created_at: string;
  type: "alpha" | "content";
  status: "pending" | "approved" | "archived";
  conviction: number;
  window: string;
  content: string;
};

type Tab = "all" | "alpha" | "content" | "pending" | "approved";

const WINDOW_COLOR: Record<string, string> = {
  open:    "var(--green)",
  closing: "var(--amber)",
  closed:  "var(--accent)",
};

export default function BriefsPage() {
  const [tab, setTab] = useState<Tab>("all");
  const [briefs, setBriefs] = useState<Brief[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<Brief | null>(null);
  const [updating, setUpdating] = useState<string | null>(null);

  const fetchBriefs = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (tab === "alpha" || tab === "content") params.set("type", tab);
      if (tab === "pending" || tab === "approved") params.set("status", tab);
      const res = await fetch(`/api/briefs?${params}`);
      const { briefs: data } = await res.json();
      setBriefs(data || []);
      if (selected) {
        const refreshed = (data || []).find((b: Brief) => b.id === selected.id);
        if (refreshed) setSelected(refreshed);
      }
    } catch { setBriefs([]); } finally { setLoading(false); }
  }, [tab, selected?.id]);

  useEffect(() => { fetchBriefs(); }, [tab]);

  async function updateStatus(id: string, status: "approved" | "archived") {
    setUpdating(id);
    try {
      await fetch("/api/briefs", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, status }),
      });
      await fetchBriefs();
    } catch { } finally { setUpdating(null); }
  }

  const pending = briefs.filter(b => b.status === "pending").length;

  return (
    <div className="max-w-[1200px] mx-auto">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="font-cond text-[clamp(1.5rem,4vw,2.2rem)] font-bold uppercase leading-none text-[var(--text-1)] tracking-[0.02em]">
            Briefs
          </h1>
          <p className="text-[0.78rem] text-[var(--text-3)] mt-2 font-light">
            Alpha and content briefs generated by the intelligence layer.
            {pending > 0 && (
              <span className="ml-2 font-mono text-[0.52rem] text-[var(--amber)] border border-[var(--amber-border)] bg-[var(--amber-dim)] px-2 py-[1px]">
                {pending} pending review
              </span>
            )}
          </p>
        </div>
        <a
          href="/command-center"
          className="font-mono text-[0.55rem] tracking-[0.12em] uppercase text-[var(--accent)] border border-[var(--accent-border)] bg-[var(--accent-dim)] px-4 py-2 no-underline hover:bg-[var(--accent)] hover:text-white transition-all"
        >
          + New signal query
        </a>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_360px] gap-4">

        {/* Left — list */}
        <div className="space-y-4">
          {/* Tabs */}
          <div className="flex gap-0 border-b border-[var(--border)]">
            {(["all", "alpha", "content", "pending", "approved"] as Tab[]).map(t => (
              <button
                key={t}
                type="button"
                onClick={() => { setTab(t); setSelected(null); }}
                className="font-mono text-[0.52rem] tracking-[0.1em] uppercase px-4 py-2 border-b-2 transition-colors"
                style={{
                  borderColor: tab === t ? "var(--accent)" : "transparent",
                  color: tab === t ? "var(--text-1)" : "var(--text-3)",
                }}
              >
                {t}
              </button>
            ))}
          </div>

          {/* List */}
          <div className="border border-[var(--border)] overflow-hidden">
            {loading ? (
              <div className="bg-[var(--bg-2)] py-16 text-center">
                <div className="inline-block w-4 h-4 border border-[var(--accent)] border-t-transparent rounded-full animate-spin mb-3" />
                <p className="font-mono text-[0.52rem] text-[var(--text-4)]">Loading briefs...</p>
              </div>
            ) : briefs.length === 0 ? (
              <div className="bg-[var(--bg-2)] py-16 px-6 text-center">
                <p className="font-mono text-[0.57rem] uppercase text-[var(--text-3)] mb-2">No briefs yet</p>
                <p className="font-mono text-[0.52rem] text-[var(--text-4)] max-w-[36ch] mx-auto leading-[1.65]">
                  Run a signal query from the overview page to generate alpha and content briefs.
                </p>
              </div>
            ) : (
              <div className="divide-y divide-[var(--border)]">
                {briefs.map(brief => {
                  let parsed: any = {};
                  try { parsed = JSON.parse(brief.content); } catch {}
                  const isSelected = selected?.id === brief.id;
                  return (
                    <div
                      key={brief.id}
                      onClick={() => setSelected(isSelected ? null : brief)}
                      className="px-4 py-3 flex items-center gap-3 cursor-pointer transition-colors"
                      style={{ background: isSelected ? "var(--bg-3)" : "var(--bg-2)" }}
                      onMouseEnter={e => { if (!isSelected) e.currentTarget.style.background = "var(--bg-3)"; }}
                      onMouseLeave={e => { if (!isSelected) e.currentTarget.style.background = "var(--bg-2)"; }}
                    >
                      {/* Type badge */}
                      <span
                        className="font-mono text-[0.44rem] tracking-[0.08em] uppercase px-2 py-[2px] border shrink-0"
                        style={{
                          color: brief.type === "alpha" ? "var(--accent)" : "var(--teal)",
                          borderColor: brief.type === "alpha" ? "var(--accent-border)" : "var(--teal-border)",
                          background: brief.type === "alpha" ? "var(--accent-dim)" : "var(--teal-dim)",
                        }}
                      >
                        {brief.type}
                      </span>

                      {/* Summary */}
                      <div className="flex-1 min-w-0">
                        <p className="text-[0.75rem] text-[var(--text-1)] truncate leading-tight">
                          {parsed.signal_summary || parsed.narrative_summary || "Brief"}
                        </p>
                        <p className="font-mono text-[0.46rem] text-[var(--text-4)] mt-[2px]">
                          {new Date(brief.created_at).toLocaleString()} · Score {brief.conviction}/10
                        </p>
                      </div>

                      {/* Window */}
                      {brief.window && (
                        <span
                          className="font-mono text-[0.42rem] uppercase shrink-0"
                          style={{ color: WINDOW_COLOR[brief.window] || "var(--text-4)" }}
                        >
                          {brief.window}
                        </span>
                      )}

                      {/* Status */}
                      <span
                        className="font-mono text-[0.44rem] tracking-[0.06em] uppercase px-2 py-[2px] border shrink-0"
                        style={{
                          color: brief.status === "approved" ? "var(--green)" : brief.status === "archived" ? "var(--text-4)" : "var(--amber)",
                          borderColor: brief.status === "approved" ? "var(--green-border)" : brief.status === "archived" ? "var(--border)" : "var(--amber-border)",
                          background: brief.status === "approved" ? "var(--green-dim)" : brief.status === "archived" ? "transparent" : "var(--amber-dim)",
                        }}
                      >
                        {brief.status}
                      </span>

                      <span className="text-[var(--text-4)] text-[0.6rem]">{isSelected ? "↑" : "↓"}</span>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Right — detail panel */}
        <div>
          {selected ? (
            <BriefDetail brief={selected} updating={updating} onUpdate={updateStatus} />
          ) : (
            <div className="border border-[var(--border)] bg-[var(--bg-2)] flex flex-col items-center justify-center py-20 text-center sticky top-6">
              <p className="font-mono text-[0.52rem] text-[var(--text-4)]">Select a brief to review</p>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}

function BriefDetail({
  brief,
  updating,
  onUpdate,
}: {
  brief: Brief;
  updating: string | null;
  onUpdate: (id: string, status: "approved" | "archived") => void;
}) {
  let parsed: any = {};
  try { parsed = JSON.parse(brief.content); } catch {}

  return (
    <div className="border border-[var(--border)] overflow-hidden sticky top-6">
      <div className="bg-[var(--bg-3)] px-4 py-2 border-b border-[var(--border)] flex items-center justify-between">
        <span
          className="font-mono text-[0.52rem] tracking-[0.12em] uppercase"
          style={{ color: brief.type === "alpha" ? "var(--accent)" : "var(--teal)" }}
        >
          {brief.type === "alpha" ? "Alpha Brief" : "Content Brief"}
        </span>
        <span className="font-mono text-[0.44rem] text-[var(--text-4)]">
          {new Date(brief.created_at).toLocaleDateString()}
        </span>
      </div>

      <div className="bg-[var(--bg-2)] p-4 space-y-4 max-h-[60vh] overflow-y-auto">
        <ConvictionBar value={brief.conviction} />

        {parsed.signal_summary && <DetailRow label="Signal" value={parsed.signal_summary} />}
        {parsed.narrative_summary && <DetailRow label="Narrative" value={parsed.narrative_summary} />}

        {parsed.chains && parsed.chains.length > 0 && (
          <div>
            <p className="font-mono text-[0.46rem] tracking-[0.12em] uppercase text-[var(--text-4)] mb-2">Chains</p>
            <div className="flex flex-wrap gap-1">
              {parsed.chains.map((c: string) => (
                <span key={c} className="font-mono text-[0.52rem] px-2 py-[2px] border border-[var(--teal-border)] bg-[var(--teal-dim)] text-[var(--teal)]">{c}</span>
              ))}
            </div>
          </div>
        )}

        {parsed.cross_chain_map && <DetailRow label="Cross-chain" value={parsed.cross_chain_map} />}
        {parsed.conviction_reasoning && <DetailRow label="Reasoning" value={parsed.conviction_reasoning} />}
        {parsed.risk_context && <DetailRow label="Risk" value={parsed.risk_context} color="var(--amber)" />}
        {parsed.pattern_match && parsed.pattern_match !== "null" && (
          <DetailRow label="Pattern match" value={parsed.pattern_match} />
        )}

        {parsed.angles && parsed.angles.length > 0 && (
          <div>
            <p className="font-mono text-[0.46rem] tracking-[0.12em] uppercase text-[var(--text-4)] mb-2">Content angles</p>
            <div className="space-y-2">
              {parsed.angles.map((a: string, i: number) => (
                <div key={i} className="flex gap-2 p-2 bg-[var(--bg)] border border-[var(--border)]">
                  <span className="font-mono text-[0.44rem] text-[var(--teal)] shrink-0">0{i+1}</span>
                  <p className="text-[0.73rem] text-[var(--text-2)] leading-[1.6]">{a}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {parsed.audience_framing && <DetailRow label="Audience framing" value={parsed.audience_framing} />}
        {parsed.evidence_links_description && (
          <DetailRow label="Evidence" value={parsed.evidence_links_description} color="var(--teal)" />
        )}

        {parsed.social_lag_hours !== undefined && (
          <div className="flex items-center justify-between py-2 border-t border-[var(--border)]">
            <span className="font-mono text-[0.46rem] text-[var(--text-4)]">Social lag</span>
            <span className="font-mono text-[0.56rem] text-[var(--green)]">{parsed.social_lag_hours}h ahead</span>
          </div>
        )}
        {parsed.window_hours !== undefined && (
          <div className="flex items-center justify-between py-2 border-t border-[var(--border)]">
            <span className="font-mono text-[0.46rem] text-[var(--text-4)]">Window remaining</span>
            <span className="font-mono text-[0.56rem]" style={{ color: WINDOW_COLOR[brief.window] || "var(--text-3)" }}>
              ~{parsed.window_hours}h
            </span>
          </div>
        )}
      </div>

      {/* Actions */}
      {brief.status === "pending" && (
        <div className="bg-[var(--bg-3)] px-4 py-3 border-t border-[var(--border)] flex gap-2">
          <button
            type="button"
            onClick={() => onUpdate(brief.id, "approved")}
            disabled={updating === brief.id}
            className="flex-1 font-mono text-[0.55rem] tracking-[0.1em] uppercase py-2 transition-all"
            style={{ background: "var(--green)", color: "#fff", opacity: updating === brief.id ? 0.6 : 1 }}
          >
            {updating === brief.id ? "Saving..." : "✓ Approve"}
          </button>
          <button
            type="button"
            onClick={() => onUpdate(brief.id, "archived")}
            disabled={updating === brief.id}
            className="font-mono text-[0.55rem] tracking-[0.1em] uppercase px-4 py-2 border border-[var(--border)] text-[var(--text-3)] transition-all hover:border-[var(--border-2)]"
          >
            Archive
          </button>
        </div>
      )}
      {brief.status === "approved" && (
        <div className="bg-[var(--bg-3)] px-4 py-3 border-t border-[var(--border)]">
          <p className="font-mono text-[0.5rem] text-[var(--green)] flex items-center gap-2">
            <span>✓</span> Approved — ready for distribution
          </p>
        </div>
      )}
    </div>
  );
}

const WINDOW_COLOR: Record<string, string> = {
  open:    "var(--green)",
  closing: "var(--amber)",
  closed:  "var(--accent)",
};

function ConvictionBar({ value }: { value: number }) {
  const color = value >= 8 ? "var(--green)" : value >= 6 ? "var(--amber)" : "var(--accent)";
  return (
    <div>
      <div className="flex items-center justify-between mb-2">
        <p className="font-mono text-[0.46rem] tracking-[0.12em] uppercase text-[var(--text-4)]">Conviction</p>
        <span className="font-mono text-[0.6rem] font-semibold" style={{ color }}>{value}/10</span>
      </div>
      <div className="h-[3px] bg-[var(--bg)] rounded-full overflow-hidden">
        <div
          className="h-full rounded-full transition-all duration-500"
          style={{ width: `${value * 10}%`, background: color }}
        />
      </div>
    </div>
  );
}

function DetailRow({ label, value, color }: { label: string; value: string; color?: string }) {
  return (
    <div>
      <p className="font-mono text-[0.46rem] tracking-[0.12em] uppercase mb-1" style={{ color: color || "var(--text-4)" }}>
        {label}
      </p>
      <p className="text-[0.77rem] text-[var(--text-2)] leading-[1.7]">{value}</p>
    </div>
  );
}
