"use client";

import { useState, useEffect, useCallback } from "react";

type Brief = {
  id: string;
  created_at: string;
  type: "alpha" | "content";
  status: "pending" | "approved" | "archived";
  conviction: number;
  window: string;
  content: string;
  signal_summary?: string;
};

type Tab = "all" | "alpha" | "content" | "pending" | "approved";

export default function BriefsPage() {
  const [tab, setTab] = useState<Tab>("all");
  const [briefs, setBriefs] = useState<Brief[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<Brief | null>(null);
  const [updating, setUpdating] = useState<string | null>(null);

  const fetchBriefs = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const params = new URLSearchParams();
      if (tab === "alpha" || tab === "content") params.set("type", tab);
      if (tab === "pending" || tab === "approved") params.set("status", tab);
      const r = await fetch(`/api/briefs?${params}`);
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const { briefs: data, error: err } = await r.json();
      if (err) throw new Error(err);
      setBriefs(data || []);
    } catch (e: any) {
      setError(e.message);
      setBriefs([]);
    } finally { setLoading(false); }
  }, [tab]);

  useEffect(() => { fetchBriefs(); }, [fetchBriefs]);

  async function updateStatus(id: string, status: "approved" | "archived") {
    setUpdating(id);
    try {
      await fetch("/api/briefs", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, status }),
      });
      setBriefs(prev => prev.map(b => b.id === id ? { ...b, status } : b));
      if (selected?.id === id) setSelected(prev => prev ? { ...prev, status } : null);
    } finally { setUpdating(null); }
  }

  const pending = briefs.filter(b => b.status === "pending").length;
  const wc = (w: string) => w === "open" ? "text-[var(--green)]" : w === "closing" ? "text-[var(--amber)]" : "text-[var(--dim)]";
  const cc = (c: number) => c >= 8 ? "text-[var(--green)]" : c >= 6 ? "text-[var(--amber)]" : "text-[var(--crimson)]";

  return (
    <div className="max-w-[1200px] mx-auto space-y-6">

      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="font-cond text-[clamp(1.5rem,4vw,2.2rem)] font-bold uppercase leading-none text-[var(--white)] tracking-[0.02em]">
            Briefs
          </h1>
          <p className="text-[0.78rem] text-[var(--low)] mt-2 font-light">
            Alpha and content briefs generated by the intelligence layer.
            {pending > 0 && (
              <span className="ml-2 font-mono text-[0.52rem] text-[var(--amber)] border border-[var(--amber-border)] bg-[var(--amber-dim)] px-2 py-[1px]">
                {pending} pending review
              </span>
            )}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button type="button" onClick={fetchBriefs}
            className="font-mono text-[0.5rem] tracking-[0.1em] uppercase text-[var(--low)] border border-[var(--border)] px-3 py-[6px] hover:text-[var(--body)] transition-colors">
            ↻ Refresh
          </button>
          <a href="/command-center"
            className="font-mono text-[0.5rem] tracking-[0.1em] uppercase text-[var(--crimson)] border border-[var(--crimson-border)] bg-[var(--crimson-dim)] px-3 py-[6px] no-underline hover:bg-[var(--crimson)] hover:text-white transition-all">
            + New query
          </a>
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="border border-[var(--crimson-border)] bg-[var(--crimson-dim)] px-4 py-3">
          <p className="font-mono text-[0.55rem] text-[var(--crimson)]">{error}</p>
          <p className="font-mono text-[0.48rem] text-[var(--muted)] mt-1">
            {error.includes("table") || error.includes("relation")
              ? "→ Run the SQL schema in Settings. Tables may not exist yet."
              : "→ Check NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY are set."}
          </p>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-[1fr_380px] gap-4">

        {/* List */}
        <div className="space-y-3">
          {/* Tabs */}
          <div className="flex border-b border-[var(--border)]">
            {(["all", "alpha", "content", "pending", "approved"] as Tab[]).map(t => (
              <button key={t} type="button" onClick={() => { setTab(t); setSelected(null); }}
                className={`font-mono text-[0.52rem] tracking-[0.1em] uppercase px-4 py-2 border-b-2 transition-colors ${
                  tab === t ? "border-[var(--crimson)] text-[var(--white)]" : "border-transparent text-[var(--low)] hover:text-[var(--body)]"
                }`}>
                {t}
              </button>
            ))}
          </div>

          {/* Brief list */}
          <div className="border border-[var(--border)] overflow-hidden">
            {loading ? (
              <div className="bg-[var(--carbon)] py-16 flex items-center justify-center gap-3">
                <span className="w-4 h-4 border border-[var(--crimson)] border-t-transparent rounded-full animate-spin" />
                <span className="font-mono text-[0.52rem] text-[var(--dim)]">Loading briefs...</span>
              </div>
            ) : briefs.length === 0 ? (
              <div className="bg-[var(--carbon)] py-16 px-6 text-center">
                <p className="font-mono text-[0.57rem] uppercase text-[var(--low)] mb-2">No briefs yet</p>
                <p className="font-mono text-[0.52rem] text-[var(--dim)] leading-[1.65] max-w-[36ch] mx-auto">
                  {error ? "Fix the error above, then run a query from the Overview page." : "Run a signal query from the Overview page to generate briefs."}
                </p>
              </div>
            ) : (
              <div className="divide-y divide-[var(--border)]">
                {briefs.map(b => {
                  let p: any = {}; try { p = JSON.parse(b.content); } catch {}
                  const isSel = selected?.id === b.id;
                  return (
                    <div key={b.id} onClick={() => setSelected(isSel ? null : b)}
                      className={`px-4 py-3 flex items-center gap-3 cursor-pointer transition-colors ${isSel ? "bg-[var(--crimson-dim)]" : "bg-[var(--carbon)] hover:bg-[var(--surface)]"}`}>
                      <span className={`font-mono text-[0.44rem] tracking-[0.08em] uppercase px-2 py-[2px] border shrink-0 ${
                        b.type === "alpha"
                          ? "text-[var(--crimson)] border-[var(--crimson-border)] bg-[var(--crimson-dim)]"
                          : "text-[var(--cyan-light)] border-[var(--cyan-border)] bg-[var(--cyan-dim)]"
                      }`}>{b.type}</span>
                      <div className="flex-1 min-w-0">
                        <p className="text-[0.75rem] text-[var(--white)] truncate leading-tight">
                          {p.signal_summary || p.narrative_summary || b.signal_summary || "Brief"}
                        </p>
                        <div className="flex items-center gap-2 mt-[3px]">
                          <span className={`font-mono text-[0.44rem] ${wc(b.window)}`}>{b.window}</span>
                          <span className="font-mono text-[0.44rem] text-[var(--dim)]">·</span>
                          <span className={`font-mono text-[0.44rem] ${cc(b.conviction)}`}>{b.conviction}/10</span>
                          <span className="font-mono text-[0.44rem] text-[var(--dim)]">·</span>
                          <span className="font-mono text-[0.44rem] text-[var(--dim)]">{new Date(b.created_at).toLocaleDateString()}</span>
                        </div>
                      </div>
                      <span className={`font-mono text-[0.44rem] tracking-[0.06em] uppercase px-2 py-[2px] border shrink-0 ${
                        b.status === "approved" ? "text-[var(--green)] border-[var(--green-border)] bg-[var(--green-dim)]"
                        : b.status === "archived" ? "text-[var(--dim)] border-[var(--border)]"
                        : "text-[var(--amber)] border-[var(--amber-border)] bg-[var(--amber-dim)]"
                      }`}>{b.status}</span>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Detail panel */}
        <div className="lg:sticky lg:top-0">
          {selected ? (() => {
            let p: any = {}; try { p = JSON.parse(selected.content); } catch {}
            const sources: string[] = p._sources || [];
            return (
              <div className="border border-[var(--border)] overflow-hidden">
                <div className="bg-[var(--surface)] px-4 py-2 border-b border-[var(--border)] flex items-center justify-between">
                  <span className={`font-mono text-[0.52rem] tracking-[0.12em] uppercase ${selected.type === "alpha" ? "text-[var(--crimson)]" : "text-[var(--cyan-light)]"}`}>
                    {selected.type === "alpha" ? "Alpha Brief" : "Content Brief"}
                  </span>
                  <span className="font-mono text-[0.44rem] text-[var(--dim)]">
                    {new Date(selected.created_at).toLocaleString()}
                  </span>
                </div>

                <div className="bg-[var(--carbon)] p-4 space-y-4 max-h-[60vh] overflow-y-auto">
                  {/* Sources */}
                  {sources.length > 0 && (
                    <div className="flex flex-wrap gap-1">
                      {sources.map(s => (
                        <span key={s} className="font-mono text-[0.42rem] uppercase tracking-[0.06em] px-[5px] py-[2px] border border-[var(--green-border)] bg-[var(--green-dim)] text-[var(--green)]">
                          ⚡ {s} live
                        </span>
                      ))}
                    </div>
                  )}

                  {/* Conviction bar */}
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="font-mono text-[0.46rem] uppercase tracking-[0.12em] text-[var(--dim)]">Conviction</span>
                      <span className={`font-mono text-[0.56rem] font-semibold ${cc(selected.conviction)}`}>{selected.conviction}/10</span>
                    </div>
                    <div className="h-[3px] bg-[var(--surface)] rounded-full overflow-hidden">
                      <div className="h-full rounded-full transition-all duration-500"
                        style={{ width: `${selected.conviction * 10}%`, background: selected.conviction >= 8 ? "var(--green)" : selected.conviction >= 6 ? "var(--amber)" : "var(--crimson)" }} />
                    </div>
                  </div>

                  {/* Fields */}
                  {[
                    { label: "Signal",         val: p.signal_summary },
                    { label: "Narrative",       val: p.narrative_summary },
                    { label: "Cross-chain",     val: p.cross_chain_map },
                    { label: "Reasoning",       val: p.conviction_reasoning },
                    { label: "Audience",        val: p.audience_framing },
                    { label: "Evidence",        val: p.evidence_links_description },
                  ].filter(r => r.val).map(row => (
                    <div key={row.label}>
                      <p className="font-mono text-[0.46rem] uppercase tracking-[0.12em] text-[var(--dim)] mb-1">{row.label}</p>
                      <p className="text-[0.75rem] text-[var(--body)] leading-[1.72]">{row.val}</p>
                    </div>
                  ))}

                  {/* Risk */}
                  {p.risk_context && (
                    <div className="border-t border-[var(--border)] pt-3">
                      <p className="font-mono text-[0.46rem] uppercase tracking-[0.12em] text-[var(--amber)] mb-1">⚠ Risk</p>
                      <p className="text-[0.75rem] text-[var(--amber)] leading-[1.72] opacity-80">{p.risk_context}</p>
                    </div>
                  )}

                  {/* Chains */}
                  {p.chains?.length > 0 && (
                    <div>
                      <p className="font-mono text-[0.46rem] uppercase tracking-[0.12em] text-[var(--dim)] mb-2">Chains</p>
                      <div className="flex flex-wrap gap-1">
                        {p.chains.map((c: string) => (
                          <span key={c} className="font-mono text-[0.48rem] px-2 py-[2px] border border-[var(--cyan-border)] bg-[var(--cyan-dim)] text-[var(--cyan-light)]">{c}</span>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Angles */}
                  {p.angles?.length > 0 && (
                    <div>
                      <p className="font-mono text-[0.46rem] uppercase tracking-[0.12em] text-[var(--dim)] mb-2">Content angles</p>
                      <div className="space-y-2">
                        {p.angles.map((a: string, i: number) => (
                          <div key={i} className="flex gap-3 p-3 bg-[var(--surface)] border border-[var(--border)]">
                            <span className="font-mono text-[0.44rem] text-[var(--cyan-light)] shrink-0">0{i+1}</span>
                            <p className="text-[0.72rem] text-[var(--body)] leading-[1.6]">{a}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Social lag */}
                  {p.social_lag_hours != null && (
                    <div className="flex items-center gap-3 border-t border-[var(--border)] pt-3">
                      <span className="font-mono text-[0.46rem] uppercase text-[var(--dim)]">Social lag</span>
                      <span className="font-mono text-[0.54rem] text-[var(--green)] font-semibold">{p.social_lag_hours}h ahead</span>
                    </div>
                  )}
                </div>

                {/* Actions */}
                {selected.status === "pending" && (
                  <div className="bg-[var(--surface)] px-4 py-3 border-t border-[var(--border)] flex gap-2">
                    <button type="button" onClick={() => updateStatus(selected.id, "approved")} disabled={!!updating}
                      className="flex-1 font-mono text-[0.55rem] tracking-[0.1em] uppercase py-2 bg-[var(--green-dim)] text-[var(--green)] border border-[var(--green-border)] hover:bg-[var(--green)] hover:text-[var(--black)] transition-all cursor-pointer flex items-center justify-center gap-2">
                      {updating === selected.id ? "Saving..." : "✓ Approve"}
                    </button>
                    <button type="button" onClick={() => updateStatus(selected.id, "archived")} disabled={!!updating}
                      className="font-mono text-[0.55rem] tracking-[0.1em] uppercase px-4 py-2 text-[var(--muted)] border border-[var(--border)] hover:border-[var(--border-md)] transition-all cursor-pointer">
                      Archive
                    </button>
                  </div>
                )}
                {selected.status === "approved" && (
                  <div className="bg-[var(--green-dim)] px-4 py-3 border-t border-[var(--green-border)]">
                    <p className="font-mono text-[0.5rem] text-[var(--green)] flex items-center gap-2">✓ Approved</p>
                  </div>
                )}
              </div>
            );
          })() : (
            <div className="border border-[var(--border)] bg-[var(--carbon)] flex items-center justify-center py-20 text-center">
              <p className="font-mono text-[0.52rem] text-[var(--dim)]">Select a brief to review</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
